apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uber-app
  namespace: argo-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argo-root
  source:
    repoURL: https://github.com/RobertFloor/nginx-gitops.git
    targetRevision: main
    path: uber
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
